# Generated by Django 5.1.3 on 2024-12-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Rating out of 5 stars", null=True
            ),
        ),
    ]
